
    let mobileMenuToggle=document.getElementById("mobileMenuToggle"),mainMenuContainer=document.getElementById("mainMenuContainer"),sideMenu=document.getElementById("sideMenuMobile"),arrowButtonSlide=document.getElementById("arrowButtonSlide"),buttonContent2=document.getElementById("buttonContent2"),programmeOverview=document.getElementById("programmeOverview"),submenuDesktop=document.getElementById("submenuDesktop"),chevronDown=document.getElementById("chevronDown");const menuMobile=document.getElementById("menuMobile"),menuItemMobile=menuMobile.getElementsByClassName("menuItemMobile"),contentSteps=document.getElementsByClassName("step"),menuDesktop=document.getElementById("menuDesktop"),menuItemDesktop=menuDesktop.getElementsByClassName("menuItemDesktop");function setActivePage(t,e,n){for(let e=0;e<t.length;e++)t[e].classList.remove("active");for(let e=0;e<contentSteps.length;e++)contentSteps[e].classList.remove("activeContent");e.classList.add("active"),n.classList.add("activeContent")}mainMenuContainer.addEventListener("click",function(){sideMenu.classList.toggle("open")});for(let e=0;e<menuItemMobile.length;e++)menuItemMobile[e].addEventListener("click",function(){setActivePage(menuItemMobile,this,contentSteps[e])});for(let e=0;e<menuItemDesktop.length;e++)menuItemDesktop[e].addEventListener("click",function(){setActivePage(menuItemDesktop,this,contentSteps[e])}),2!==e&&3!==e&&4!==e&&e&&menuItemDesktop[e].addEventListener("click",function(){submenuDesktop.classList.remove("activeDropdown"),chevronDown.classList.remove("rotate")});buttonContent2.addEventListener("click",function(){contentSteps[0].classList.remove("activeContent"),contentSteps[1].classList.add("activeContent"),menuItemDesktop[0].classList.remove("active"),menuItemDesktop[1].classList.add("active"),menuItemMobile[0].classList.remove("active"),menuItemMobile[1].classList.add("active")}),programmeOverview.addEventListener("click",function(){submenuDesktop.classList.toggle("activeDropdown"),chevronDown.classList.toggle("rotate");for(let e=0;e<contentSteps.length;e++)2!==e&&contentSteps[e].addEventListener("click",function(){submenuDesktop.classList.remove("activeDropdown")}),contentSteps[e].classList.remove("activeContent");for(let e=0;e<menuItemDesktop.length;e++)2!==e&&menuItemDesktop[e].classList.remove("active");for(let e=0;e<menuItemMobile.length;e++)2!==e&&menuItemMobile[e].classList.remove("active");contentSteps[2].classList.add("activeContent"),menuItemDesktop[2].classList.add("active"),menuItemMobile[2].classList.add("active")});

// Add the same click event for other menuItemDesktop elements if needed

document.getElementById('closeButtonModal').addEventListener('click', function() {
    document.getElementById('modalPage').style.display = 'none';
});
	
